[package]
name = "kernel"
version = "0.1.0"
authors = ["Michael Melanson <michael@michaelmelanson.net>"]
edition = "2018"

[dependencies]
log = { version = "0.4", default-features = false }
hashbrown = "0.6.3"
